"use client";

import { Order } from "@/types";
import { COURIER_PAYOUT_SYMBOL } from "@/lib/constants";
import { formatPayoutAmount } from "@/lib/courierSwap";

interface Props {
  order: Order;
  role?: "patient" | "courier";
}

function hashString(str: string): string {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) - hash + str.charCodeAt(i)) | 0;
  }
  return Math.abs(hash).toString(16).padStart(8, "0").toUpperCase();
}

export default function Receipt({ order, role = "patient" }: Props) {
  const proofHash = hashString(
    `${order.id}${order.patientWalletHash || order.patientWallet || "redacted"}${order.amount}${order.paidAt}`
  );
  const payerHash = order.patientWalletHash || "not-recorded";
  const payoutSymbol = order.payoutTokenSymbol || COURIER_PAYOUT_SYMBOL;
  const payoutAmountDisplay = order.payoutAmount ? formatPayoutAmount(order.payoutAmount, 2) : "N/A";
  const paidAtIso = new Date(order.paidAt || order.createdAt).toISOString();
  const serviceDateIso = new Date(order.deliveredAt || order.paidAt || order.createdAt).toISOString();
  const complianceSignatureDigest = order.complianceSignature
    ? order.complianceSignature.slice(0, 22)
    : "not-attached";
  const claimReference = `PD-${hashString(
    `${order.id}|${order.complianceAttestationId || "none"}|${order.complianceApprovalCode || "none"}`
  )}`;

  function downloadPatientInsuranceReceipt() {
    const content = [
      "════════════════════════════════════════════",
      " PHANTOMDROP PATIENT RECEIPT (INSURANCE)",
      "════════════════════════════════════════════",
      "",
      `Claim Reference:         ${claimReference}`,
      `Order ID:                ${order.id}`,
      `Service Date (ISO):      ${serviceDateIso}`,
      `Settlement Date (ISO):   ${paidAtIso}`,
      `Medication Category:     ${order.medicationType}`,
      `Delivery Address:        ${order.dropLocation}`,
      "",
      "COMPLIANCE RECORD",
      `Attestation ID:          ${order.complianceAttestationId || "missing"}`,
      `Approval Code:           ${order.complianceApprovalCode || "missing"}`,
      `Doctor Token:            ${order.complianceDoctorToken || "missing"}`,
      `Patient Token:           ${order.compliancePatientToken || "missing"}`,
      `Compliance Signature:    ${complianceSignatureDigest}`,
      `Authorization Expires:   ${order.complianceExpiresAt || "missing"}`,
      "",
      "PAYMENT EVIDENCE",
      "Pricing:                 Private (ZK-shielded)",
      `Settlement Token:        ${payoutSymbol}`,
      `Escrow Funding Relay:    ${order.escrowDepositRelayId || "not-recorded"}`,
      `Escrow Settlement Relay: ${order.escrowSendRelayId || "not-recorded"}`,
      `Payout Reference:        ${order.payoutTxHash || order.payoutSwapReference || "not-recorded"}`,
      `ZK Proof Digest:         0x${proofHash}...`,
      "",
      "PATIENT IDENTITY PROTECTION",
      `Patient Wallet Hash:     ${payerHash}`,
      "",
      "Generated by PhantomDrop for insurance documentation support.",
      "════════════════════════════════════════════",
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `patient-insurance-receipt-${order.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadCourierStatement() {
    const content = [
      "════════════════════════════════════════════",
      " PHANTOMDROP COURIER PAYMENT STATEMENT",
      "════════════════════════════════════════════",
      "",
      `Statement ID:            PAY-${hashString(`${order.id}|${order.paidAt || 0}`)}`,
      `Order ID:                ${order.id}`,
      `Issued By:               PhantomDrop`,
      `Payout Date (ISO):       ${paidAtIso}`,
      `Service Date (ISO):      ${serviceDateIso}`,
      "",
      "PAYEE",
      `Courier Wallet:          ${order.courierWallet || "missing"}`,
      "",
      "PAYMENT DETAILS",
      `Payout Amount:           ${payoutAmountDisplay} ${payoutSymbol}`,
      `Payout Reference:        ${order.payoutTxHash || order.payoutSwapReference || "not-recorded"}`,
      `Settlement Relay ID:     ${order.escrowSendRelayId || "not-recorded"}`,
      "",
      "TAX NOTE",
      "This statement is provided by PhantomDrop as payment evidence.",
      "Consult your tax advisor for jurisdiction-specific filing requirements.",
      "════════════════════════════════════════════",
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `courier-payment-statement-${order.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (role === "courier") {
    return (
      <div className="border border-zinc-100 p-5 space-y-4">
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <p className="font-mono text-xs text-zinc-400">{order.id}</p>
            <p className="text-xs font-bold uppercase tracking-widest text-zinc-900">Courier Payment Statement</p>
            <p className="text-xs text-zinc-400">{new Date(order.paidAt || order.createdAt).toLocaleDateString()}</p>
          </div>
          <span className="text-[10px] px-2 py-0.5 border border-zinc-900/20 text-zinc-700 bg-zinc-50 uppercase tracking-widest font-bold">
            Courier
          </span>
        </div>

        <div className="border border-zinc-100 bg-zinc-50 p-3 font-mono text-xs space-y-1.5">
          <div className="flex justify-between">
            <span className="text-zinc-400 uppercase tracking-wide">Payout</span>
            <span className="text-zinc-700">{payoutAmountDisplay} {payoutSymbol}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-zinc-400 uppercase tracking-wide">Issued By</span>
            <span className="text-zinc-600">PhantomDrop</span>
          </div>
          <div className="flex justify-between">
            <span className="text-zinc-400 uppercase tracking-wide">Reference</span>
            <span className="text-zinc-600">{(order.payoutTxHash || order.payoutSwapReference || "not-recorded").slice(0, 18)}...</span>
          </div>
        </div>

        <button
          onClick={downloadCourierStatement}
          className="w-full py-2.5 border border-zinc-200 text-xs text-zinc-600 uppercase tracking-widest hover:border-zinc-900 hover:text-zinc-900 transition-colors"
        >
          Download Courier Statement →
        </button>
      </div>
    );
  }

  return (
    <div className="border border-zinc-100 p-5 space-y-4">
      <div className="flex items-start justify-between">
        <div className="space-y-1">
          <p className="font-mono text-xs text-zinc-400">{order.id}</p>
          <p className="text-xs font-bold uppercase tracking-widest text-zinc-900">Patient Insurance Receipt</p>
          <p className="text-xs text-zinc-400">
            {new Date(order.paidAt || order.createdAt).toLocaleDateString()}
          </p>
        </div>
        <span className="text-[10px] px-2 py-0.5 border border-[#00E100]/40 text-[#00E100] bg-green-50 uppercase tracking-widest font-bold">
          Patient
        </span>
      </div>

      <div className="border border-zinc-100 bg-zinc-50 p-3 font-mono text-xs space-y-1.5">
        <div className="flex justify-between">
          <span className="text-zinc-400 uppercase tracking-wide">Medication</span>
          <span className="text-zinc-600">{order.medicationType}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-zinc-400 uppercase tracking-wide">Claim Ref</span>
          <span className="text-zinc-600">{claimReference}</span>
        </div>
        <div className="flex justify-between">
          <span className="text-zinc-400 uppercase tracking-wide">Pricing</span>
          <span className="text-zinc-500 italic">ZK shielded</span>
        </div>
        <div className="flex justify-between">
          <span className="text-zinc-400 uppercase tracking-wide">ZK Proof</span>
          <span className="text-[#00E100]">0x{proofHash}...</span>
        </div>
        {order.complianceAttestationId && (
          <div className="flex justify-between">
            <span className="text-zinc-400 uppercase tracking-wide">Compliance</span>
            <span className="text-[#00E100]">{order.complianceAttestationId.slice(0, 16)}...</span>
          </div>
        )}
        {order.complianceApprovalCode && (
          <div className="flex justify-between">
            <span className="text-zinc-400 uppercase tracking-wide">Approval</span>
            <span className="text-zinc-600">{order.complianceApprovalCode}</span>
          </div>
        )}
      </div>

      <button
        onClick={downloadPatientInsuranceReceipt}
        className="w-full py-2.5 border border-zinc-200 text-xs text-zinc-600 uppercase tracking-widest hover:border-zinc-900 hover:text-zinc-900 transition-colors"
      >
        Download Patient Receipt →
      </button>
    </div>
  );
}
